apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  labels:
    {{- include "masking-proxy.labels" . | nindent 4 }}
  name: {{ include "masking-proxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ include "masking-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}