apiVersion: v1
data:
{{- with .Values.argocd.maskingProxyCluster }}
  config: {{ .config | b64enc }}
  name: {{ .name | b64enc }}
  server: {{ .server | b64enc }}
{{- end }}
kind: Secret
metadata:
  annotations:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: {{ include "masking-proxy.fullname" . }}
  namespace: argocd
type: Opaque