apiVersion: v1
kind: Service
metadata:
  labels:
     {{- include "masking-proxy.labels" . | nindent 4 }}
  name: {{ include "masking-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "masking-proxy.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}