apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: masking-proxy
  name: masking-proxy
  namespace: argocd
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3003
    protocol: TCP
    targetPort: 3003
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3003
  selector:
    app.kubernetes.io/name: masking-proxy
  sessionAffinity: None
  type: ClusterIP